[package]
name = "track_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.131.0"
rand = "0.8.5"
tokio = { version = "1.34.0", features = ["full"] }